### ISSUE TITLE
Initial true doesn't call enter on element creation

### ISSUE THREAD

**Issue by minht11** [otonashixav/solid-flip#4]
I am not sure if I am misunderstanding something, but documentation says `Used to apply initial styling. Also accepts a boolean; if true, calls enter`

Based on [my testing](https://codesandbox.io/s/objective-germain-oeuwh?file=/index.js:450-473) it doesn't do that when page loads, so this might be a bug. Previously `appear` property worked as intended.

**Comment by otonashixav** [comment]
I know what's causing it, will fix it soon.

**Comment by otonashixav** [comment]
Fixed in 0.7.4.
