### ISSUE TITLE
During animation the same element is rendered multiple times

### ISSUE THREAD

**Issue by minht11** [otonashixav/solid-flip#8]
[Reproduction](https://codesandbox.io/s/clever-chatterjee-f0m277?file=/index.js:702-703)
Multiple times press the toggle button and observe that there are multiple DOM elements instead of one.

<img width="165" alt="image" src="https://user-images.githubusercontent.com/8914032/162062990-65554c3d-f3cb-4673-8e18-851670c20329.png">

```tsx
const App = () => {
  const [isVisible, setIsVisible] = createSignal(true);

  return (
    <div>
      <button onClick={() => setIsVisible((v) => !v)}>Toggle</button>
      <TransitionGroup
        enter={animateEnter({
          keyframes: {
            opacity: [0, 1]
          },
          options: { duration: 2000, easing: "linear" }
        })}
        exit={animateExit({
          keyframes: {
            opacity: [1, 0]
          },
          options: { duration: 2000, easing: "linear" }
        })}
      >
        {isVisible() && <div class="element" />}
      </TransitionGroup>
    </div>
  );
};
```

**Comment by otonashixav** [comment]
This is because a new div is created whenever `isVisible()` is toggled. If you don't want this behaviour then you need to make the div persistent regardless of the condition e.g. 
```jsx
const el = <div class="element" />;
// ...
{isVisible() && el}
```
or via whatever other methods.

**Comment by minht11** [comment]
Solid 1.4 update fixed all of my issues. I don't see the duplication anymore on route change.
