### ISSUE TITLE
Fix css file tab in playground example in README

### ISSUE THREAD

**Issue by aquaductape** [otonashixav/solid-flip#9]
Issue loading playground link example from README.

The issue is due to index.css file tab is actually a tsx extension, you have to update it to use .css extension

Playground Error: 
```
Could not load ./index.css (imported by ./main): Cannot access the file system (via "fs.readFile") when using the browser build of Rollup. Make sure you supply a plugin with custom resolveId and load hooks to Rollup.
```

Broken link in README: https://playground.solidjs.com/anonymous/6d232892-85ce-435e-9f48-0886fbab01f5

Fixed link where index.tsx is renamed to index.css: https://playground.solidjs.com/anonymous/b41605b0-a6fb-437e-b158-05e37c443bd7

**Comment by otonashixav** [comment]
Thanks.
